version: '3.4'

services:
  loki_discord_bot:
    image: loki_discord_bot
    build: .
    environment:
      NODE_ENV: production
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 80:80